CXX=g++
# g++ knows how to link in the c++ runtime and dylibs correctly; without it, we
# would have to replicate the link line that g++ uses.
#LD=ld
LD:=$(CXX)
LDFLAGS+=-arch i386 -mmacosx-version-min=10.7 -stdlib=libc++

CPPFLAGS=\
        -g \
        -arch i386 \
        -mmacosx-version-min=10.7 \
        -stdlib=libc++ \
        `/usr/local/bin/nspr-config --cflags`

LDLIBS=`/usr/local/bin/nspr-config --libs`

include Makefile
