CXX=g++
# g++ knows how to link in the c++ runtime and dylibs correctly; without it, we
# would have to replicate the link line that g++ uses.
#LD=ld
LD:=$(CXX)
LDFLAGS+=-arch i386

ifndef NSPR
NSPR=/usr/local
endif

CPPFLAGS=\
        -g \
        -arch i386 \
        -mmacosx-version-min=10.7 \
        -stdlib=libc++ \
        `$(NSPR)/bin/nspr-config --cflags`

LDLIBS=`$(NSPR)/bin/nspr-config --libs`

include Makefile
