CXX=g++
# Not entirely sure why we can't use ld directly...
#LD=ld
LD:=$(CXX)

CPPFLAGS=\
        -DNEGATUS_LINUX_DESKTOP_BUILD \
        -g --std=gnu++0x \
	$(shell nspr-config --cflags)

LDLIBS=$(shell nspr-config --libs) -lrt

include Makefile
